name: Build Test

on:
  pull_request:
  push:
    paths:
      - .github/workflows/ktlint.yml
      - 'src/**/*.kt'
      - '**.kts'

jobs:
  ktlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: ./gradlew ktlintCheck

